name: Trigger dispatch-b's package update

on:
    workflow_run:
        workflows: [pr]
        types: [completed]

jobs:
    trigger-dispatch-b:
        if: github.event.workflow_run.conclusion == 'success':
        runs-on: ubuntu-latest
        steps:
        - uses: actions/github-script@v6
        with:
            github-token: ${{ secrets.TRIGGER_DISPATCH_B }}
            script: |
            await github.rest.actions.createworkflowDispatch({
                owner: 'scaramallion',
                repo: 'dispatch-b',
                workflow_id: 'receiver',
                ref: 'main',
            })
